### ISSUE TITLE
is it possible to do these same as in es6

### ISSUE THREAD

**Issue by SelvaraniAlagumuthu** [iannbing/react-simple-tree-menu#119]
Need to do the same functionality in react-native also please guide me to do that. i am totally new in react-native and also i don't know typescript also.

**Comment by iannbing** [comment]
I'm not sure how I can help you here 😊

I can only give you some suggestions:
1. Copy the source code piece by piece into your React Native project, replace the HTML element with React Native equivalent, such as `View` and `Text`, and see if it works.
2. You don't need `KeyDown.tsx` since this behavior doesn't apply on mobile.
3. you can learn Typescript along the way. or simply use js instead of ts and remove the typings.

I'll close this issue, since you're not actually reporting an issue 😊
Happy coding!
