### ISSUE TITLE
Provide a reset function to reset the openNodes

### ISSUE THREAD

**Issue by iannbing** [iannbing/react-simple-tree-menu#78]
Sometimes user just wants to reset the `openNodes`, and the only thing needs to be done is to provide a way to set internal state.

**Comment by iannbing** [comment]
pre-released `1.1.4-rc.1`

**Comment by agentS** [comment]
Thank you so much for your changes!

I tried to port the code from the story to my program; it now seems that when rendering custom buttons one also needs to come up with a custom layout for the items. Is there any way I can reuse the minimal default visualization since it is good enough for my requirements?

**Comment by iannbing** [comment]
It's definitely possible. Just export the default UI components so you can extend it. I'll consider adding this in the same release. I'm quite busy these days.
