### ISSUE TITLE
Another On Open question

### ISSUE THREAD

**Issue by JasonLunsford** [iannbing/react-simple-tree-menu#88]
Opening a new issue as the prior question is closed.

I would like to hook into the collapse/expand onClick event (the event that occurs when the icon is clicked, not when the node itself is clicked). In the prior question this code was given:

<ToggleIcon on={isOpen} onClick={() => {
    toggleNode();
    yourOwnFunction();
   }} 
   />

This definitely helps a little bit, but what I still don't understand is where this code is meant to go? Is it possible to use this code without creating a custom "MyTreeMenu" component?

Or, is it just possible to surface this functionality by default? Maybe call the prop onNodeToggle or something?

Thanks (again)!

**Comment by iannbing** [comment]
Since toggleIcon is inside of ItemComponent, you cannot alter it’s behavior from outside. So you do need to create your own ItemComponent.

**Comment by JasonLunsford** [comment]
I apologize for being dense, but could you elaborate on that? I'm not familiar with your code base. Maybe provide a simple (but complete) example? My aim here is to hook into the onClick event for the toggle action so I can dynamically load data when the node is expanded.

Thank you for your help and patience.

**Comment by iannbing** [comment]
I think your question is more about React in general rather than the library itself. The README and the story is quite extensive to demonstrate the API. 

I can only help you if you could share your code, such as codesandbox. If you figure out, feel free to send PR to add your usecase to the example [story](https://github.com/iannbing/react-simple-tree-menu/blob/master/stories/index.stories.js).

**Comment by iannbing** [comment]
I'll close this issue since it is more about a React question.

**Comment by iannbing** [comment]
Feel free to share your code, and I am happy to give advice.
