### ISSUE TITLE
Expand/Collapse all nodes

### ISSUE THREAD

**Issue by Alannek1992** [iannbing/react-simple-tree-menu#98]
Hello,

I ve found out, that you provide a reset functionality to operate on openNodes. I am just curious about the data structure of the openNodes. Basically its a "itemA/itemB" etc. Do I have to write my own algorithm, which transform my data, which are being passed to TreeMenu into this form "key/key" etc. I am just wondering if there is a more smooth way to do that :).

BR,
Ales.

**Comment by iannbing** [comment]
Yes, and it's intentional.

If the default expand/close behaviour meets your requirement, you only need to provide `data`. But if you have specific requirements, then you have to implement your own logic, this `TreeMenu` component allows you to manipulate almost everything.

`openNodes` is used when you want to have full control over every node, and you don't want the default expand/close behaviour AT ALL. You can see the storybook example [here](https://iannbing.github.io/react-simple-tree-menu/?path=/story/treemenu--control-treemenu-from-its-parent). I guess this API is rarely used. 

If you only want to set the tree to a specific shape but still allow users to use the tree menu, you can use `initialOpenNodes`, see example [here](https://iannbing.github.io/react-simple-tree-menu/?path=/story/treemenu--reset-opennodes). This API is more useful I guess.
